### ISSUE TITLE
Support Bitbucket

### ISSUE THREAD

**Issue by mpppk** [mpppk/hlb#1]
# TODO
- [ ] Support `browse` command
    - [ ] `browse`
    - [ ] `browse issues`
    - [ ] `browse pull-requests`
- [ ] Support `list` command
    - [ ] `list issues`
    - [ ] `list pull-requests`
